# Generated by Django 2.2.6 on 2019-10-30 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_triplelink'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Activity',
            new_name='Action',
        ),
        migrations.RenameField(
            model_name='triplelink',
            old_name='activity',
            new_name='action',
        ),
        migrations.AlterModelTable(
            name='action',
            table='action',
        ),
        migrations.CreateModel(
            name='ActionAnomaly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase1', models.IntegerField()),
                ('phrase2', models.IntegerField()),
                ('action1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Action')),
                ('action2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Action')),
            ],
            options={
                'db_table': 'action_anomaly',
            },
        ),
    ]
